# Generated by Django 4.0.4 on 2022-06-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('Dis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=50)),
                ('team2', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('matchdate', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('discription', models.TextField()),
            ],
        ),
    ]
