# Generated by Django 4.0.4 on 2022-06-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_upcomeing_matches_matchcompleated'),
    ]

    operations = [
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='videos/')),
                ('link', models.URLField(max_length=500)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
