# Generated by Django 4.0.4 on 2022-06-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_upcomeing_dis'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='status',
            field=models.CharField(choices=[('trending', 'trending'), ('recent', 'recent')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
