# Generated by Django 4.0.4 on 2022-06-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_blogs_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NEWS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='news/')),
                ('name', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('discription', models.TextField()),
            ],
        ),
    ]
