# Generated by Django 4.0.4 on 2022-06-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomeing',
            name='createdAt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
