# Generated by Django 4.0.4 on 2022-06-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_upcomeing_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='createdAt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
