# Generated by Django 4.0.4 on 2022-06-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_blogs_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomeing',
            name='logoofTeam1',
            field=models.ImageField(default=0, upload_to='blogs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upcomeing',
            name='createdAt',
            field=models.DateTimeField(),
        ),
    ]
