# Generated by Django 4.0.4 on 2022-06-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_upcomeing_logoofteam1_alter_upcomeing_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='logoofTeam1',
            field=models.ImageField(default=0, upload_to='blogs/'),
            preserve_default=False,
        ),
    ]
