# Generated by Django 4.0.4 on 2022-06-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_matches_logoofteam1'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='logoofTeam2',
            field=models.ImageField(default=0, upload_to='blogs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomeing',
            name='logoofTeam2',
            field=models.ImageField(default=0, upload_to='blogs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matches',
            name='logoofTeam1',
            field=models.ImageField(upload_to='teams/'),
        ),
        migrations.AlterField(
            model_name='upcomeing',
            name='logoofTeam1',
            field=models.ImageField(upload_to='teams/'),
        ),
    ]
