# Generated by Django 4.0.4 on 2022-08-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_matches_logoofteam2_upcomeing_logoofteam2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ans', models.IntegerField(default=1)),
            ],
        ),
    ]
