# Generated by Django 4.0.2 on 2022-02-26 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='play',
        ),
    ]
