# Generated by Django 4.0.4 on 2022-06-09 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerdata',
            old_name='age',
            new_name='DateOfBirth',
        ),
    ]
