# Generated by Django 4.0.4 on 2022-06-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_rename_age_playerdata_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdata',
            name='cat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
