# Generated by Django 3.2.12 on 2022-04-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_playerdata_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerdata',
            name='age',
            field=models.CharField(max_length=200),
        ),
    ]
