# Generated by Django 4.0.4 on 2022-05-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_alter_playerdata_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdata',
            name='GamesNo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='playerdata',
            name='Goals',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='playerdata',
            name='Height',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='playerdata',
            name='JersyNo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='playerdata',
            name='Losses',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='playerdata',
            name='Nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='playerdata',
            name='Weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='playerdata',
            name='Wins',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
