# Generated by Django 4.0.4 on 2022-05-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiview', '0002_stateassociations'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateassociations',
            name='Email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stateassociations',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stateassociations',
            name='mobile',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stateassociations',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='stateassociations',
            name='position',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
