# Generated by Django 4.0.4 on 2022-05-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiview', '0003_stateassociations_email_stateassociations_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthletesCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='BoardManageMent/')),
                ('position', models.CharField(max_length=100)),
                ('AssociatedTeam', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('AndhraPradesh', 'AndhraPradesh'), ('ArunachalPradesh', 'ArunachalPradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'haryana'), ('HimachalPradesh', 'HimachalPradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('MadhyaPradesh', 'MadhyaPradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('TamilNadu', 'TamilNadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttarakhand', 'Uttarakhand'), ('UttarPradesh', 'UttarPradesh'), ('WestBengal', 'WestBengal')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BoardManageMent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='BoardManageMent/')),
                ('position', models.CharField(max_length=100)),
                ('AssociatedTeam', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('AndhraPradesh', 'AndhraPradesh'), ('ArunachalPradesh', 'ArunachalPradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'haryana'), ('HimachalPradesh', 'HimachalPradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('MadhyaPradesh', 'MadhyaPradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('TamilNadu', 'TamilNadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttarakhand', 'Uttarakhand'), ('UttarPradesh', 'UttarPradesh'), ('WestBengal', 'WestBengal')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SelectionCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='BoardManageMent/')),
                ('position', models.CharField(max_length=100)),
                ('AssociatedTeam', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('AndhraPradesh', 'AndhraPradesh'), ('ArunachalPradesh', 'ArunachalPradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'haryana'), ('HimachalPradesh', 'HimachalPradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('MadhyaPradesh', 'MadhyaPradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('TamilNadu', 'TamilNadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttarakhand', 'Uttarakhand'), ('UttarPradesh', 'UttarPradesh'), ('WestBengal', 'WestBengal')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='stateassociations',
            name='photo',
            field=models.ImageField(blank=True, upload_to='StateAssociationsAll/'),
        ),
    ]
