# Generated by Django 4.0.4 on 2022-05-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiview', '0005_allaccouncements_leagues_matches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagues',
            name='photo',
            field=models.ImageField(default=0, upload_to='leagues/'),
            preserve_default=False,
        ),
    ]
